POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbGxlOTk5IiwiaWQiOiI1ZjFhNDI4MDg0ZjMyOTJkYzhkYTE4NjciLCJpYXQiOjE1OTU1NTY3NjJ9.4sdax_YlnXln505NaN47EhFcnjS0JAIN7FDfIr3FKHo

{
    "author": "Matti Partanen",
    "title": "Don't fear the reaper",
    "url": "https://reaper.com"
}